# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: BMT_GANstopping
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
  - anaconda

dependencies:
  - python=3.9
  - pytorch=2.0
  - torchvision=0.15
  - pytorch-cuda=11.8
  - pytorch-lightning
  - pip
  - wandb
  - pip:
    - albumentations
    - rich
    - weightwatcher
    - torchmetrics[image]
    - pyefd